# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a905de0adc198f412e181fb66cf45056f6e344e6d2d655ba5e01821a15f4fca24af39069f3cdef07d620b6af5c0e460db1e51cfda78c0ec43e61396fb2c09171

test:
  secret_key_base: 23a5ea9d84bad3ad05afdd60caed2f9a57464db057702d08a0be979254acd754bc19ab454437d7299e211a84a9e45865f043532072c9f3ca236e9066441bf680

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
